# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8166afd2d1824c0b62a9cc46c33e854e19353b425c06820f118758a4f98e03c838da9e0cc1432ad8d5dc42469e6bc8f808af4d5647550b31ff20ffe11c435b8f 

test:
  secret_key_base: 8166afd2d1824c0b62a9cc46c33e854e19353b425c06820f118758a4f98e03c838da9e0cc1432ad8d5dc42469e6bc8f808af4d5647550b31ff20ffe11c435b8f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 8166afd2d1824c0b62a9cc46c33e854e19353b425c06820f118758a4f98e03c838da9e0cc1432ad8d5dc42469e6bc8f808af4d5647550b31ff20ffe11c435b8f
